version: '3'

services:
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: sunny
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb



  nextcloudos:
    image: nextcloud:18.0.4-apache
    restart: always
    depends_on:
      - dbos
    ports:
      - 8899:80
    environment:
      NEXTCLOUD_ADMIN_USER: root
      NEXTCLOUD_ADMIN_PASSWORD: root
    volumes:
      - cn_storage_new:/var/www/html

volumes:
  cn_storage_new:
  mysql_storage_new:










            
